name: printing_pos
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0-190.1.beta

# Add regular dependencies here.
dependencies:
  esc_pos_dart: ^1.0.4
  intl: ^0.19.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
